"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import "./globals.css";
import Sidebar from "@/components/SideBar";
import Navbar from "@/components/Navbar";
import ShowCase from "@/components/ShowCase";
import MediaURLContext from "@/context/MediaURLContext";
import { useState } from "react";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
  children: React.ReactNode;
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


function RootLayout({ children }: LayoutProps) {

  const [mediaURL, setMediaURL] = useState<string>('');
  const [audioURL, setAudioURL] = useState<string>('');
  const [mediaFile, setMediaFile] = useState<File | null>(null);
  const [audioFile, setAudioFile] = useState<File | null>(null);

  return (
    <html lang="en">
      <body className={inter.className}>

        <MediaURLContext.Provider value={{ mediaURL, setMediaURL, audioURL, setAudioURL, mediaFile, setMediaFile, audioFile, setAudioFile }}>
          <MantineProvider withGlobalClasses withCssVariables>
            <main className="flex flex-col h-screen">
              <Navbar />
              <div className="flex flex-1 overflow-hidden">
                <Sidebar />
                {children}
                <ShowCase />
              </div>
              <Footer />
            </main>
          </MantineProvider>
        </MediaURLContext.Provider>

      </body>
    </html>
  );
}

export default RootLayout;